name: Build manylinux Pyhton wheels

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/manylinux-wheels.yml'
      - 'python/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'setup.py'

jobs:
  build_wheels:
    strategy:
      matrix:
        python-version: [ 'cp37-cp37m', 'cp38-cp38', 'cp39-cp39', 'cp310-cp310' ]

    name: Build manylinux wheel for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine flake8

      - name: Lint with flake8 for syntax errors
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build manylinux Python wheel
        #uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux_2_24_x86_64
        uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
        with:
          python-versions: ${{ matrix.python-version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: manylinux-wheels
          path: dist/*manylinux*.whl

    #- name: Publish wheels to PyPI
    #  env:
    #    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #  run: |
    #    twine upload dist/*-manylinux*.whl